const GpuConfig = [
  {
    name: 'NVIDIA T1000',
    tier: 'Entry 1',
    shortName: 't1000',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.044,
    gpuPricePerMonth: 31.5,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 1,
    vendor: 'nvidia',
    value: '1',
    disabled: false,
  },
  {
    name: 'NVIDIA Tesla p4',
    tier: 'Entry 1',
    shortName: 'p4',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.046,
    gpuPricePerMonth: 32.9,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 2,
    vendor: 'nvidia',
    value: '2',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1050',
    tier: 'Entry 1',
    shortName: 'gtx1050',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 3,
    vendor: 'nvidia',
    value: '3',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1050 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1050ti',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.07,
    gpuPricePerMonth: 50.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 4,
    vendor: 'nvidia',
    value: '4',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1060',
    tier: 'Entry 1',
    shortName: 'gtx1060',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 5,
    vendor: 'nvidia',
    value: '5',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1070',
    tier: 'Entry 1',
    shortName: 'gtx1070',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 6,
    vendor: 'nvidia',
    value: '6',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1070 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1070ti',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.07,
    gpuPricePerMonth: 50.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 7,
    vendor: 'nvidia',
    value: '7',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1080',
    tier: 'Entry 1',
    shortName: 'gtx1080',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.053,
    gpuPricePerMonth: 37.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 8,
    vendor: 'nvidia',
    value: '8',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1080 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1080ti',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.072,
    gpuPricePerMonth: 51.84,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 9,
    vendor: 'nvidia',
    value: '9',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2060',
    tier: 'Entry 1',
    shortName: 'rtx2060',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.045,
    gpuPricePerMonth: 32.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 10,
    vendor: 'nvidia',
    value: '10',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2060 Super',
    tier: 'Entry 1',
    shortName: 'rtx2060super',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.055,
    gpuPricePerMonth: 39.6,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 11,
    vendor: 'nvidia',
    value: '11',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2070',
    tier: 'Entry 1',
    shortName: 'rtx2070',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 12,
    vendor: 'nvidia',
    value: '12',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2080',
    tier: 'Entry 2',
    shortName: 'rtx2080',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 37.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 13,
    vendor: 'nvidia',
    value: '13',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2080 Super',
    tier: 'Entry 2',
    shortName: 'rtx2080super',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.056,
    gpuPricePerMonth: 40.32,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 14,
    vendor: 'nvidia',
    value: '14',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3050',
    tier: 'Entry 2',
    shortName: 'rtx3050',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.051,
    gpuPricePerMonth: 36.72,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 15,
    vendor: 'nvidia',
    value: '15',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3050 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3050ti',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.055,
    gpuPricePerMonth: 39.6,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 62,
    vendor: 'nvidia',
    value: '62',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3060',
    tier: 'Entry 2',
    shortName: 'rtx3060',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.052,
    gpuPricePerMonth: 37.44,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 16,
    vendor: 'nvidia',
    value: '16',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3060 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3060ti',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.058,
    gpuPricePerMonth: 41.76,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 17,
    vendor: 'nvidia',
    value: '17',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3070',
    tier: 'Entry 2',
    shortName: 'rtx3070',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.052,
    gpuPricePerMonth: 37.44,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 18,
    vendor: 'nvidia',
    value: '18',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3070 Ti',
    tier: 'Entry 2',
    shortName: 'rtx3070ti',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.063,
    gpuPricePerMonth: 45.5,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 19,
    vendor: 'nvidia',
    value: '19',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4060',
    tier: 'Entry 2',
    shortName: 'rtx4060',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.055,
    gpuPricePerMonth: 39.6,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 20,
    vendor: 'nvidia',
    value: '20',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4060 Ti',
    tier: 'Entry 2',
    shortName: 'rtx4060ti',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.065,
    gpuPricePerMonth: 46.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 21,
    vendor: 'nvidia',
    value: '21',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4070',
    tier: 'Entry 2',
    shortName: 'rtx4070',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.058,
    gpuPricePerMonth: 41.76,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 22,
    vendor: 'nvidia',
    value: '22',
    disabled: false,
  },
  {
    name: 'NVIDIA Tesla P100 PCIe',
    tier: 'Entry 2',
    shortName: 'p100',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.06,
    gpuPricePerMonth: 43.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 23,
    vendor: 'nvidia',
    value: '23',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX A4000',
    tier: 'Entry 2',
    shortName: 'rtxa4000',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.081,
    gpuPricePerMonth: 58.1,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 24,
    vendor: 'nvidia',
    value: '24',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2080 Ti',
    tier: 'Low 1',
    shortName: 'rtx2080ti',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.07,
    gpuPricePerMonth: 50.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 25,
    vendor: 'nvidia',
    value: '25',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3080',
    tier: 'Low 1',
    shortName: 'rtx3080',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.07,
    gpuPricePerMonth: 50.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 26,
    vendor: 'nvidia',
    value: '26',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3080 Ti',
    tier: 'Low 1',
    shortName: 'rtx3080ti',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.072,
    gpuPricePerMonth: 51.84,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 27,
    vendor: 'nvidia',
    value: '27',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4070 Ti',
    tier: 'Low 1',
    shortName: 'rtx4070ti',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.075,
    gpuPricePerMonth: 54.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 28,
    vendor: 'nvidia',
    value: '28',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4000',
    tier: 'Low 1',
    shortName: 'rtx4000',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.06,
    gpuPricePerMonth: 43.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 29,
    vendor: 'nvidia',
    value: '29',
    disabled: false,
  },
  {
    name: 'NVIDIA P40',
    tier: 'Low 1',
    shortName: 'p40',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.085,
    gpuPricePerMonth: 61.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 30,
    vendor: 'nvidia',
    value: '30',
    disabled: false,
  },
  {
    name: 'NVIDIA Tesla T4',
    tier: 'Low 1',
    shortName: 't4',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.035,
    gpuPricePerMonth: 25.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 31,
    vendor: 'nvidia',
    value: '31',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4080',
    tier: 'Low 2',
    shortName: 'rtx4080',
    multiplier: 0.75,
    fn: 500,
    gpuPricePerHour: 0.085,
    gpuPricePerMonth: 61.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 32,
    vendor: 'nvidia',
    value: '32',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4080 Super',
    tier: 'Low 2',
    shortName: 'rtx4080super',
    multiplier: 0.75,
    fn: 500,
    gpuPricePerHour: 0.09,
    gpuPricePerMonth: 64.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 64,
    vendor: 'nvidia',
    value: '64',
    disabled: false,
  },
  {
    name: 'NVIDIA Titan RTX',
    tier: 'Low 2',
    shortName: 'titanrtx',
    multiplier: 0.75,
    fn: 500,
    gpuPricePerHour: 0.132,
    gpuPricePerMonth: 95.05,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 33,
    vendor: 'nvidia',
    value: '33',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3090',
    tier: 'Low 2',
    shortName: 'rtx3090',
    multiplier: 0.75,
    fn: 500,
    gpuPricePerHour: 0.126,
    gpuPricePerMonth: 90.65,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 34,
    vendor: 'nvidia',
    value: '34',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 3090 Ti',
    tier: 'Low 2',
    shortName: 'rtx3090ti',
    multiplier: 0.75,
    fn: 500,
    gpuPricePerHour: 0.148,
    gpuPricePerMonth: 106.56,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 35,
    vendor: 'nvidia',
    value: '35',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4090',
    tier: 'Medium 1',
    shortName: 'rtx4090',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.175,
    gpuPricePerMonth: 126.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 36,
    vendor: 'nvidia',
    value: '36',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX A5000',
    tier: 'Medium 1',
    shortName: 'rtxa5000',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.088,
    gpuPricePerMonth: 63.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 37,
    vendor: 'nvidia',
    value: '37',
    disabled: false,
  },
  {
    name: 'NVIDIA A10',
    tier: 'Medium 1',
    shortName: 'a10',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.091,
    gpuPricePerMonth: 65.45,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 38,
    vendor: 'nvidia',
    value: '38',
    disabled: false,
  },
  {
    name: 'NVIDIA A10G',
    tier: 'Medium 1',
    shortName: 'a10g',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.123,
    gpuPricePerMonth: 88.2,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 39,
    vendor: 'nvidia',
    value: '39',
    disabled: false,
  },
  {
    name: 'NVIDIA L4',
    tier: 'Medium 1',
    shortName: 'l4',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.098,
    gpuPricePerMonth: 71.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 40,
    vendor: 'nvidia',
    value: '40',
    disabled: false,
  },
  {
    name: 'NVIDIA Tesla V100',
    tier: 'Medium 1',
    shortName: 'v100',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.088,
    gpuPricePerMonth: 63.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 41,
    vendor: 'nvidia',
    value: '41',
    disabled: false,
  },
  {
    name: 'NVIDIA Tesla V100S',
    tier: 'Medium 1',
    shortName: 'v100s',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.092,
    gpuPricePerMonth: 66.24,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 61,
    vendor: 'nvidia',
    value: '61',
    disabled: false,
  },
  {
    name: 'NVIDIA A40',
    tier: 'Medium 1',
    shortName: 'a40',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.112,
    gpuPricePerMonth: 79.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 42,
    vendor: 'nvidia',
    value: '42',
    disabled: false,
  },
  {
    name: 'NVIDIA L40',
    tier: 'Medium 2',
    shortName: 'l40',
    multiplier: 1.5,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 43,
    vendor: 'nvidia',
    value: '43',
    disabled: true,
  },
  {
    name: 'NVIDIA RTX 8000',
    tier: 'Medium 2',
    shortName: 'rtx8000',
    multiplier: 1.5,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 44,
    vendor: 'nvidia',
    value: '44',
    disabled: true,
  },
  {
    name: 'NVIDIA RTX A6000',
    tier: 'Medium 2',
    shortName: 'rtxa6000',
    multiplier: 1.5,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 45,
    vendor: 'nvidia',
    value: '45',
    disabled: true,
  },
  {
    name: 'NVIDIA L40S',
    tier: 'High 1',
    shortName: 'l40s',
    multiplier: 2,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 46,
    vendor: 'nvidia',
    value: '46',
    disabled: true,
  },
  {
    name: 'NVIDIA RTX 6000 Ada',
    tier: 'High 1',
    shortName: 'rtx6000-ada',
    multiplier: 2,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 47,
    vendor: 'nvidia',
    value: '47',
    disabled: true,
  },
  {
    name: 'NVIDIA A100 PCIE 40GB',
    tier: 'High 2',
    shortName: 'a100-pcie-40g',
    multiplier: 3,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 48,
    vendor: 'nvidia',
    value: '48',
    disabled: true,
  },
  {
    name: 'NVIDIA A100 SXM4 40GB',
    tier: 'High 2',
    shortName: 'a100-sxm-40g',
    multiplier: 3,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 49,
    vendor: 'nvidia',
    value: '49',
    disabled: true,
  },
  {
    name: 'NVIDIA A100 80GB',
    tier: 'Ultra High 1',
    shortName: 'a100-80g',
    multiplier: 6,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 50,
    vendor: 'nvidia',
    value: '50',
    disabled: true,
  },
  {
    name: 'NVIDIA H100 80G',
    tier: 'Ultra High 2',
    shortName: 'h100',
    multiplier: 12,
    fn: 500,
    gpuPricePerHour: 0,
    gpuPricePerMonth: 0,
    cpuPricePerMonth: 0,
    ramPricePerGbPerMonth: 0,
    storagePricePerGbPerMonth: 0,
    id: 51,
    vendor: 'nvidia',
    value: '51',
    disabled: true,
  },
  {
    name: 'NVIDIA GTX 1650',
    tier: 'Entry 1',
    shortName: 'gtx1650',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.04,
    gpuPricePerMonth: 28.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 52,
    vendor: 'nvidia',
    value: '52',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1660',
    tier: 'Entry 1',
    shortName: 'gtx1660',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.04,
    gpuPricePerMonth: 28.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 53,
    vendor: 'nvidia',
    value: '53',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1660 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1660ti',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 54,
    vendor: 'nvidia',
    value: '54',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1660 Super',
    tier: 'Entry 1',
    shortName: 'gtx1660super',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.055,
    gpuPricePerMonth: 39.6,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 55,
    vendor: 'nvidia',
    value: '55',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4070 Ti Super',
    tier: 'Low 1',
    shortName: 'rtx4070tisuper',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.078,
    gpuPricePerMonth: 56.16,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 56,
    vendor: 'nvidia',
    value: '56',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4050',
    tier: 'Entry 2',
    shortName: 'rtx4050',
    multiplier: 0.25,
    fn: 500,
    gpuPricePerHour: 0.055,
    gpuPricePerMonth: 39.6,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 57,
    vendor: 'nvidia',
    value: '57',
    disabled: false,
  },
  {
    name: 'NVIDIA GTX 1650 Ti',
    tier: 'Entry 1',
    shortName: 'gtx1650ti',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.05,
    gpuPricePerMonth: 36.0,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 58,
    vendor: 'nvidia',
    value: '58',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4000 Ada',
    tier: 'Medium 1',
    shortName: 'rtx4000-ada',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.14,
    gpuPricePerMonth: 100.8,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 59,
    vendor: 'nvidia',
    value: '59',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4000 SFF Ada',
    tier: 'Medium 1',
    shortName: 'rtx4000-sff-ada',
    multiplier: 1,
    fn: 500,
    gpuPricePerHour: 0.145,
    gpuPricePerMonth: 104.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 63,
    vendor: 'nvidia',
    value: '63',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 2050',
    tier: 'Entry 1',
    shortName: 'rtx2050',
    multiplier: 0.1,
    fn: 500,
    gpuPricePerHour: 0.042,
    gpuPricePerMonth: 30.4,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 60,
    vendor: 'nvidia',
    value: '60',
    disabled: false,
  },
  {
    name: 'NVIDIA RTX 4070 Super',
    tier: 'Low 1',
    shortName: 'rtx4070super',
    multiplier: 0.5,
    fn: 500,
    gpuPricePerHour: 0.077,
    gpuPricePerMonth: 55.44,
    cpuPricePerMonth: 0.75,
    ramPricePerGbPerMonth: 0.1,
    storagePricePerGbPerMonth: 0.01,
    id: 65,
    vendor: 'nvidia',
    value: '65',
    disabled: false,
  },
];

export default GpuConfig;
